#!/usr/bin/env bash
set -Eeuo pipefail
APP="$HOME/kubeheal-app"
NS="kubeheal-system"
IMAGE="kubeheal:5.1"
log(){ printf '\n[KubeHeal 5.1] %s\n' "$1"; }
[[ -f "$APP/app.py" ]] || { echo "KubeHeal source not found"; exit 1; }

log "Restoring full navigation while retaining Phase 5 incident details"
cat > "$APP/templates/dashboard.html" <<'HTML'
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KubeHeal</title>
<style>*{box-sizing:border-box}body{margin:0;font:14px Arial;background:#f5f7fb;color:#172033}.side{position:fixed;width:210px;height:100vh;background:#10223d;color:#fff;padding:22px 16px}.brand{font-size:23px;font-weight:700;margin:0 0 28px}.nav{padding:12px 14px;border-radius:7px;margin:5px 0;cursor:pointer}.nav:hover,.nav.active{background:#3673df}.main{margin-left:210px;padding:30px}.top{display:flex;justify-content:space-between;align-items:center}.view{display:none}.view.active{display:block}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,.panel{background:#fff;border:1px solid #dce3ec;border-radius:9px;padding:20px;margin-bottom:18px}.num{font-size:30px;font-weight:700}.green{color:#14954f}.red{color:#df3535}.orange{color:#d47d00}.muted{color:#6e7b8d}.badge{padding:6px 11px;border-radius:15px;background:#ddf8e8;color:#08783d;font-weight:700}.bad{background:#ffe1e1;color:#b32121}.bar{height:8px;background:#e5eaf1;border-radius:8px;margin:12px 0}.fill{height:100%;background:#20a760;border-radius:8px}table{border-collapse:collapse;width:100%}th,td{padding:11px;border-bottom:1px solid #e8edf3;text-align:left}button{border:0;border-radius:6px;background:#246de1;color:#fff;padding:10px 14px;cursor:pointer}.danger{background:#e43b37}.state{min-height:245px}.pod{background:#f4f7fa;margin:5px 0;padding:7px;border-radius:5px}.step{border-left:3px solid #20a760;padding:8px;margin:5px}.metric{font-size:34px;font-weight:700}.setting{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eee}@media(max-width:900px){.side{display:none}.main{margin-left:0}.grid4,.grid3{grid-template-columns:1fr}}</style></head>
<body><aside class="side"><div class="brand">⬡ KubeHeal</div><div class="nav active" data-page="dashboard">Dashboard</div><div class="nav" data-page="applications">Applications</div><div class="nav" data-page="pods">Pods</div><div class="nav" data-page="incidents">Incidents</div><div class="nav" data-page="experiments">Experiments</div><div class="nav" data-page="metrics">Metrics</div><div class="nav" data-page="settings">Settings</div></aside>
<main class="main"><div class="top"><div><h1 id="title">Dashboard</h1><div class="muted" id="subtitle">Kubernetes Application Health & Auto-Recovery</div></div><div class="green">● Cluster Connected</div></div>
<section id="dashboard" class="view active"><div class="grid4"><div class="card">Applications<div class="num" id="ca">-</div></div><div class="card">Pods<div class="num" id="cp">-</div></div><div class="card">Active Incidents<div class="num red" id="ci">-</div></div><div class="card">Recoveries<div class="num green" id="cr">-</div></div></div><div class="panel"><h2>Application Health</h2><div id="dashApps" class="grid3"></div></div><div class="panel"><h2>Cluster Resource Usage</h2><div class="grid3"><div>CPU<div id="cpu" class="metric">-</div></div><div>Memory<div id="memory" class="metric">-</div></div><div>Pods<div id="podMetric" class="metric">-</div></div></div></div></section>
<section id="applications" class="view"><div id="appCards" class="grid3"></div></section>
<section id="pods" class="view"><div class="panel"><table><thead><tr><th>Pod</th><th>Application</th><th>Phase</th><th>Ready</th><th>Restarts</th></tr></thead><tbody id="podRows"></tbody></table></div></section>
<section id="incidents" class="view"><div class="panel"><h2>Incident History</h2><table><thead><tr><th>ID</th><th>Application</th><th>Issue</th><th>Severity</th><th>Status</th><th>Recovery Action</th><th>Time</th><th></th></tr></thead><tbody id="incidentRows"></tbody></table></div><div id="detail"></div></section>
<section id="experiments" class="view"><div class="grid3"><div class="card"><h2>Crash Pod</h2><p>Delete a backend pod and observe native replacement.</p><button class="danger" onclick="runExp('crash')">Trigger Crash</button></div><div class="card"><h2>Pod Not Ready</h2><p>Temporarily remove backend availability, then restore it.</p><button onclick="runExp('not-ready')">Trigger Not Ready</button></div><div class="card"><h2>Restart Deployment</h2><p>Perform a controlled backend rollout restart.</p><button onclick="runExp('restart')">Trigger Restart</button></div></div><p id="msg"></p></section>
<section id="metrics" class="view"><div class="grid3"><div class="card"><h3>CPU Usage</h3><div id="mCpu" class="metric">-</div></div><div class="card"><h3>Memory Usage</h3><div id="mMemory" class="metric">-</div></div><div class="card"><h3>Pods</h3><div id="mPods" class="metric">-</div></div></div><div class="panel"><p class="muted">Per-application historical charts will be added after workload instrumentation.</p></div></section>
<section id="settings" class="view"><div class="panel"><h2>Health & Recovery Policy</h2><div class="setting"><span>CPU warning</span><b>75%</b></div><div class="setting"><span>CPU critical</span><b>90%</b></div><div class="setting"><span>Memory warning</span><b>75%</b></div><div class="setting"><span>Memory critical</span><b>90%</b></div><div class="setting"><span>Recovery verification</span><b>Enabled</b></div></div></section>
</main><script>
const titles={dashboard:['Dashboard','Kubernetes Application Health & Auto-Recovery'],applications:['Applications','Manage and monitor Kubernetes applications'],pods:['Pods','Live pod state'],incidents:['Incidents','Before, during, recovery action and after state'],experiments:['Experiments','Controlled demo-only fault scenarios'],metrics:['Metrics','Prometheus resource metrics'],settings:['Settings','Health and recovery policy']};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.getElementById(n.dataset.page).classList.add('active');title.textContent=titles[n.dataset.page][0];subtitle.textContent=titles[n.dataset.page][1]});
function appCard(a){return `<div class="card"><div style="display:flex;justify-content:space-between"><h2>${a.name}</h2><span class="badge ${a.status==='healthy'?'':'bad'}">${a.status}</span></div><div class="num">${a.ready}/${a.desired} Ready</div><div class="bar"><div class="fill" style="width:${a.desired?100*a.ready/a.desired:0}%"></div></div></div>`}
function snap(s){if(!s)return '<div class="state"><b>Waiting for snapshot...</b></div>';return `<div class="state"><h3>${s.label}</h3><div class="num ${s.health==='HEALTHY'?'green':'red'}">${s.health}</div><p>Captured: ${s.captured_at}</p><p>Replicas: <b>${s.ready}/${s.desired}</b></p><p>CPU: <b>${s.cpu_cores} cores</b></p><p>Memory: <b>${s.memory_mib} MiB</b></p><b>Pods</b>${s.pods.map(p=>`<div class="pod">${p.name}<br>${p.ready?'Ready':'Not Ready'} | Restarts ${p.restarts}</div>`).join('')}</div>`}
async function refresh(){let d=await (await fetch('/api/summary',{cache:'no-store'})).json();ca.textContent=d.counts.applications;cp.textContent=d.counts.pods;ci.textContent=d.counts.active;cr.textContent=d.counts.recoveries;cpu.textContent=mCpu.textContent=d.cpu+'%';memory.textContent=mMemory.textContent=d.memory+'%';podMetric.textContent=mPods.textContent=d.counts.pods;dashApps.innerHTML=appCards.innerHTML=d.applications.map(appCard).join('');podRows.innerHTML=d.pods.map(p=>`<tr><td>${p.name}</td><td>${p.app}</td><td>${p.phase}</td><td class="${p.ready?'green':'red'}">${p.ready?'Ready':'Not Ready'}</td><td>${p.restarts}</td></tr>`).join('');incidentRows.innerHTML=d.incidents.map(i=>`<tr><td>#${i.id}</td><td>${i.application}</td><td>${i.type}</td><td>${i.severity}</td><td class="${i.status==='RECOVERED'?'green':'red'}">${i.status}</td><td>${i.recovery_action}</td><td>${i.recovery_seconds?i.recovery_seconds+'s':'-'}</td><td><button onclick="details(${i.id})">View</button></td></tr>`).join('')||'<tr><td colspan="8">No incidents yet</td></tr>'}
async function details(id){let i=await (await fetch('/api/incidents/'+id,{cache:'no-store'})).json();detail.innerHTML=`<div class="panel"><h2>Incident #${i.id}: ${i.application} - ${i.type}</h2><p><b>Status:</b> ${i.status} | <b>Severity:</b> ${i.severity}</p><p><b>Recovery action:</b> ${i.recovery_action}</p><p><b>Recovery owner:</b> ${i.recovery_owner}</p><p><b>Old pods:</b> ${i.old_pods.join(', ')||'-'}</p><p><b>New pods:</b> ${i.new_pods.join(', ')||'-'}</p><p><b>Recovery time:</b> ${i.recovery_seconds?i.recovery_seconds+' sec':'in progress'}</p><h3>Recovery Progress</h3>${i.progress.map(x=>`<div class="step">✓ ${x}</div>`).join('')}<h2>Before → During → After</h2><div class="grid3">${snap(i.before)}${snap(i.during)}${snap(i.after)}</div></div>`}
async function runExp(k){msg.textContent='Creating '+k+' incident...';let r=await fetch('/api/experiments/'+k,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({application:'backend'})});let d=await r.json();msg.textContent=d.ok?'Incident #'+d.incident.id+' created. Open Incidents to watch recovery.':'Experiment failed';refresh()}
refresh();setInterval(refresh,1200);
</script></body></html>
HTML

log "Building $IMAGE"
cd "$APP"
minikube image build -t "$IMAGE" .
log "Updating deployment"
kubectl -n "$NS" set image deployment/kubeheal kubeheal="$IMAGE"
kubectl rollout status deployment/kubeheal -n "$NS" --timeout=180s
log "Full Phase 5.1 UI restored"
kubectl get pods -n "$NS"
echo; echo "Hard-refresh the browser (Ctrl+Shift+R). All navigation options are restored."
